version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
  - package-ecosystem: docker
    directory: .buildkite
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
