linters:
  enable:
  - gofmt
  - nolintlint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # dont worry about checking error returns in test files
    - path: _test.go
      linters:
        - errcheck
