project_name: bk
version: 2

release:
  name_template: Buildkite CLI {{.Version}}
  draft: true
  replace_existing_draft: true
  prerelease: auto
  make_latest: false
  mode: replace

changelog:
  use: github

brews:
  - name: bk@3
    ids:
      - macos-archive
      - linux-archive
    directory: .
    caveats: |
      This is beta software

      For any questions, issues or feedback, please file an issue at https://github.com/buildkite/cli/issues
    homepage: https://github.com/buildkite/cli
    description: Work with Buildkite from the command-line
    license: MIT
    skip_upload: false
    test: system "#{bin}/bk --version"
    repository:
      owner: buildkite
      name: homebrew-buildkite
      branch: master

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: bk
    main: ./cmd/bk
    ldflags:
      - -s -w -X github.com/buildkite/cli/v3/internal/version.Version={{.Version}}

  - id: linux
    goos: [linux]
    goarch: ['386', arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bk
    main: ./cmd/bk
    ldflags:
      - -s -w -X github.com/buildkite/cli/v3/internal/version.Version={{.Version}}

  - id: windows
    goos: [windows]
    goarch: ['386', amd64, arm64]
    binary: bk
    main: ./cmd/bk
    ldflags:
      - -s -w -X github.com/buildkite/cli/v3/internal/version.Version={{.Version}}

archives:
  - id: macos-archive
    builds: [macos]
    name_template: "bk_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: zip
    files:
      - LICENSE.md
      - README.md

  - id: linux-archive
    builds: [linux]
    name_template: "bk_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE.md
      - README.md

  - id: windows-archive
    builds: [windows]
    name_template: "bk_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE.md
      - README.md

nfpms:
  - builds:
      - linux
    vendor: Buildkite
    homepage: https://buildkite.com
    maintainer: Buildkite <support@buildkite.com>
    description: A command line interface for Buildkite.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    provides:
      - bk

# vim: set ts=2 sw=2 tw=0 fo=cnqoj
