project_name: bk

release:
  name_template: Buildkite CLI {{.Version}}
  draft: true
  replace_existing_draft: true
  prerelease: auto
  make_latest: false
  mode: replace

changelog:
  use: github

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: bin/bk
    main: ./cmd/bk
    ldflags:
      - -s -w -X github.com/buildkite/cli/v3/internal/version.Version={{.Version}}

  - id: linux
    goos: [linux]
    goarch: ['386', arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/bk
    main: ./cmd/bk
    ldflags:
      - -s -w -X github.com/buildkite/cli/v3/internal/version.Version={{.Version}}

  - id: windows
    goos: [windows]
    goarch: ['386', amd64, arm64]
    binary: bin/bk
    main: ./cmd/bk
    ldflags:
      - -s -w -X github.com/buildkite/cli/v3/internal/version.Version={{.Version}}

archives:
  - id: macos-archive
    builds: [macos]
    name_template: "bk_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: zip
    files:
      - LICENSE.md
      - README.md

  - id: linux-archive
    builds: [linux]
    name_template: "bk_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE.md
      - README.md

  - id: windows-archive
    builds: [windows]
    name_template: "bk_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE.md
      - README.md

# vim: set ts=2 sw=2 tw=0 fo=cnqoj
