# This uses the upstream image without any changes intentionally.
# This allows dependabot to keep this version up-to-date for us automatically, since it does not work with
# docker-compose directly
FROM goreleaser/goreleaser-pro:v2.13.3@sha256:34eed2b04907d777ed443e4190262f0d9882b4b03c61a9783eee996ac8b7c657
