# This uses the upstream image without any changes intentionally.
# This allows dependabot to keep this version up-to-date for us automatically, since it does not work with
# docker-compose directly
FROM goreleaser/goreleaser-pro:v2.3.1-pro@sha256:9706f408afc05e18528c3840c6e58cb2359346ca860d51030d1c6638058a2358
