agents:
  queue: hosted

steps:
  - name: ":golangci-lint: lint"
    plugins:
      docker-compose#v5.1.0:
        config: .buildkite/docker-compose.yaml
        run: lint
        tty: true

  - name: ":go: test"
    artifact_paths:
      - cover-tree.svg
    plugins:
      docker-compose#v5.1.0:
        config: .buildkite/docker-compose.yaml
        run: test
        tty: true

  - wait

  - label: ":buildkite: build"
    artifact_paths:
      - dist/**/*
    plugins:
      docker-compose#v5.1.0:
        config: .buildkite/docker-compose.yaml
        run: build
        tty: true
