agents:
  queue: hosted

steps:
  - name: ":golangci-lint: lint"
    plugins:
      golangci-lint#dev:
        config: .golangci.yaml 
        timeout: "3m"
        create_annotations: true

  - name: ":go: test"
    artifact_paths:
      - cover-tree.svg
    commands:
      - go test -coverprofile cover.out ./...
      - go run github.com/nikolaydubina/go-cover-treemap@latest -coverprofile cover.out > cover-tree.svg
      - echo '<details><summary>Coverage tree map</summary><img src="artifact://cover-tree.svg" alt="Test coverage tree map" width="70%"></details>' | buildkite-agent annotate --style "info"
    plugins:
      -  docker-compose#v5.2.0:
          config: .buildkite/docker-compose.yaml
          run: golangci-lint
          tty: true
          mount-buildkite-agent: true

  - wait

  - label: ":terminal: build ({{matrix}})"
    matrix:
          - "darwin"
          - "linux"
          - "windows"
    artifact_paths:
      - dist/**/*
    plugins:
      - docker-compose#v5.2.0:
          command:
            - .buildkite/release.sh
            - release
            - --clean
            - --snapshot
            - --split
          config: .buildkite/docker-compose.yaml
          entrypoint: /bin/sh
          env:
            - GOOS={{matrix}}
          mount-buildkite-agent: true
          run: goreleaser
          shell: false
          tty: true

  - block: ":package: Create a release?"
    prompt: "Fill out the tag to create for this release"
    branches:
      - main
    blocked_state: passed
    fields:
      - key: release-tag
        text: Tag
        required: true
        hint: "Eg: v3.0.0-beta.rev2"

  # this tags the commit with the input from the previous block step and pushes it to github
  # that will trigger the buildkite-cli-release pipeline off the tag which will create a release in github
  - label: ":rocket: Pushing a tag to release"
    command: ".buildkite/tag.sh"
    branches:
      - main
    env:
      AWS_REGION: us-east-1
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-buildkite-cli
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.0.0:
          parameters:
            GITHUB_TOKEN: /pipelines/buildkite/buildkite-cli/github-token
            GITHUB_USER: /pipelines/buildkite/buildkite-cli/github-user
