agents:
  queue: hosted

x-cache-env: &cache_env
  GOCACHE: .buildkite/cache-volume/go/build
  GOMODCACHE: .buildkite/cache-volume/go/pkg/mod
  GOLANGCI_LINT_CACHE: .buildkite/cache-volume/golangci-lint

x-mise-plugin: &mise_plugin
  buildkite-plugins/mise#v1.1.0: ~

cache: ".buildkite/cache-volume"

steps:
  - name: ":golangci-lint: lint"
    commands:
      - '. "${BUILDKITE_ENV_FILE}"'
      - golangci-lint run --verbose --timeout 3m
    env:
      <<: *cache_env
    plugins:
      - *mise_plugin

  - name: ":go: test"
    artifact_paths:
      - cover-tree.svg
    env:
      <<: *cache_env
    commands:
      - '. "${BUILDKITE_ENV_FILE}"'
      - go test -coverprofile cover.out ./...
      - go run github.com/nikolaydubina/go-cover-treemap@v1.5.1 -coverprofile cover.out > cover-tree.svg
      - echo '<details><summary>Coverage tree map</summary><img src="artifact://cover-tree.svg" alt="Test coverage tree map" width="70%"></details>' | buildkite-agent annotate --style "info"
    plugins:
      - *mise_plugin

  - wait

  - label: ":terminal: build ({{matrix}})"
    matrix:
          - "darwin"
          - "linux"
          - "windows"
    artifact_paths:
      - dist/**/*
    secrets:
      - POSTHOG_API_KEY
      - OAUTH_CLIENT_ID
    env:
      <<: *cache_env
      GOOS: "{{matrix}}"
    commands:
      - '. "${BUILDKITE_ENV_FILE}"'
      - .buildkite/release.sh release --clean --snapshot --split
    plugins:
      - *mise_plugin

  - input: ":package: Create a release?"
    prompt: "Select the release type"
    key: release_unblock
    branches:
      - main
    allowed_teams:
      - "support"
      - "deploy"
    blocked_state: "passed"
    fields:
      - key: release-type
        select: "Release Type"
        required: true
        options:
          - label: "Patch (v3.x.X)"
            value: "patch"
          - label: "Minor (v3.X.0)"
            value: "minor"
          - label: "Major (vX.0.0) - Manual only"
            value: "major"

  # this tags the commit with the input from the previous block step and pushes it to github
  # that will trigger the buildkite-cli-release pipeline off the tag which will create a release in github
  - label: ":rocket: Pushing a tag to release"
    command: ".buildkite/tag.sh"
    depends_on: release_unblock
    branches:
      - main
    env:
      AWS_REGION: us-east-1
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-buildkite-cli
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.1.0:
          parameters:
            GITHUB_TOKEN: /pipelines/buildkite/buildkite-cli/github-token
            GITHUB_USER: /pipelines/buildkite/buildkite-cli/github-user
