steps:
  - name: ":golangci-lint: lint"
    plugins:
      docker-compose#v4.14.0:
        config: .buildkite/docker-compose.yaml
        run: lint

  - name: ":go: test"
    plugins:
      docker-compose#v4.14.0:
        config: .buildkite/docker-compose.yaml
        run: test

  - wait

  - label: ":buildkite: build"
    artifact_paths:
      - dist/**/*
    plugins:
      docker-compose#v4.14.0:
        config: .buildkite/docker-compose.yaml
        run: build
