steps:
  - name: "Lint"
    command: ".buildkite/steps/lint.sh"
    plugins:
      docker#v5.8.0:
        image: "golang:1.20"

  - name: "Test"
    command: "go test -v -failfast ./..."
    plugins:
      docker-compose#v4.14.0:
        config: .buildkite/docker-compose.yml
        run: agent

  - wait
  - name: "Test with Local Agent"
    command: ".buildkite/steps/run-local.sh"
    plugins:
      docker-compose#v4.14.0:
        config: .buildkite/docker-compose.yml
        run: agent

  - wait
  - label: ":golang:"
    command: make build
    plugins:
      golang#v2.0.0:
        version: 1.20.0
        environment:
          - RELEVANCE_API_URL
          - RELEVANCE_PROJECT
          - FUN_RELEVANT_PROJECT
          - FUN_RELEVANCE_API_URL
    artifact_paths:
      - "build/*"
