agents:
  queue: hosted

steps:
  - name: ":golangci-lint: lint"
    command: golangci-lint run --verbose --timeout 3m
    plugins:
      docker-compose#v5.1.0:
        config: .buildkite/docker-compose.yaml
        run: golangci-lint
        tty: true

  - name: ":go: test"
    artifact_paths:
      - cover-tree.svg
    commands:
      - go test -coverprofile cover.out ./...
      - go run github.com/nikolaydubina/go-cover-treemap@latest -coverprofile cover.out > cover-tree.svg
      - echo '<details><summary>Coverate tree map</summary><img src="artifact://cover-tree.svg" alt="Test coverage tree map" height=500></details>' | buildkite-agent annotate --style "info"
    plugins:
      docker-compose#v5.1.0:
        config: .buildkite/docker-compose.yaml
        run: golangci-lint
        tty: true
        mount-buildkite-agent: true

  - wait

  - label: ":buildkite: build"
    artifact_paths:
      - dist/**/*
    plugins:
      docker-compose#v5.1.0:
        config: .buildkite/docker-compose.yaml
        run: build
        tty: true
