agents:
  queue: hosted

cache: ".buildkite/cache-volume"

steps:
  - label: ":terminal: build ({{matrix}})"
    key: build
    matrix:
          - "darwin"
          - "linux"
          - "windows"
    artifact_paths:
      - dist/**/*
    secrets:
      - MISE_GITHUB_TOKEN
      - POSTHOG_API_KEY
      - OAUTH_CLIENT_ID
    command: 'GOOS="{{matrix}}" .buildkite/release.sh release --clean --split'
    plugins:
      - mise#v1.1.1: ~

  - label: ":rocket: :package: upload packages ({{matrix}})"
    key: upload_packages
    depends_on: build
    matrix:
      - "deb"
      - "rpm"
    command: '.buildkite/upload-packages.sh "{{matrix}}"'
    plugins:
      - artifacts#v1.9.4:
          download:
            - dist/linux/*

  - label: ":rocket: :github: release"
    key: release
    depends_on: ["build", "upload_packages"]
    artifact_paths:
      - dist/**/*
    env:
      AWS_REGION: us-east-1
    secrets:
      - MISE_GITHUB_TOKEN
      - POSTHOG_API_KEY
      - OAUTH_CLIENT_ID
    plugins:
      - aws-assume-role-with-web-identity#v1.5.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-buildkite-cli-release
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.1.0:
          parameters:
            GITHUB_TOKEN: /pipelines/buildkite/buildkite-cli-release/github-token
            DOCKERHUB_USER: /pipelines/buildkite/buildkite-cli-release/dockerhub-user
            DOCKERHUB_PASSWORD: /pipelines/buildkite/buildkite-cli-release/dockerhub-password
      - artifacts#v1.9.4:
          download:
            - dist/**/*
      - mise#v1.1.1: ~
    command: '.buildkite/release.sh continue --merge'
