package secret

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

const migrationManifestPrefix = "# buildkite-gha-migration: "

type migrationManifest struct {
	Version           int      `json:"version"`
	Organization      string   `json:"organization"`
	Cluster           string   `json:"cluster"`
	Policy            string   `json:"policy"`
	Repository        string   `json:"repository"`
	RepositoryID      int64    `json:"repository_id"`
	RepositoryOwnerID int64    `json:"repository_owner_id"`
	DefaultBranch     string   `json:"default_branch"`
	SecretNames       []string `json:"secret_names"`
}

func encodeMigrationManifest(manifest migrationManifest) (string, error) {
	data, err := json.Marshal(manifest)
	if err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(data), nil
}

func decodeMigrationManifest(workflow []byte) (migrationManifest, error) {
	line, _, found := bytes.Cut(workflow, []byte("\n"))
	if !found || !bytes.HasPrefix(line, []byte(migrationManifestPrefix)) {
		return migrationManifest{}, errors.New("workflow was not generated by a supported secrets migration prepare command")
	}
	data, err := base64.RawURLEncoding.DecodeString(strings.TrimPrefix(string(line), migrationManifestPrefix))
	if err != nil {
		return migrationManifest{}, errors.New("workflow has an invalid migration manifest")
	}
	var manifest migrationManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return manifest, errors.New("workflow has an invalid migration manifest")
	}
	if manifest.Version != 1 || !organizationSlugPattern.MatchString(manifest.Organization) || !uuidPattern.MatchString(manifest.Cluster) || manifest.RepositoryID == 0 || manifest.RepositoryOwnerID == 0 || manifest.Repository == "" || manifest.DefaultBranch == "" || len(manifest.SecretNames) == 0 {
		return manifest, errors.New("workflow migration manifest is incomplete")
	}
	policy, err := validateSecretsPolicy(manifest.Policy)
	if err != nil || policy != manifest.Policy {
		return manifest, errors.New("workflow migration manifest has an invalid access policy")
	}
	for index, name := range manifest.SecretNames {
		if err := validateMigrationSecretName(name); err != nil || name == "GITHUB_TOKEN" || (index > 0 && name <= manifest.SecretNames[index-1]) {
			return manifest, errors.New("workflow migration manifest has an invalid secret allowlist")
		}
	}
	return manifest, nil
}

// renderOIDCSecretsMigrationWorkflow intentionally remains byte-compatible with
// buildkite-gha v0.90.0 so either CLI can run an already reviewed workflow.
func renderOIDCSecretsMigrationWorkflow(manifest migrationManifest) ([]byte, error) {
	encodedManifest, err := encodeMigrationManifest(manifest)
	if err != nil {
		return nil, fmt.Errorf("encode migration manifest: %w", err)
	}
	var output strings.Builder
	fmt.Fprintf(&output, `%s%s
# One-use GitHub-to-Buildkite secrets migration.
# Source: %s (repository ID %d, owner ID %d)
# Destination: %s cluster %s
# Access policy:
`, migrationManifestPrefix, encodedManifest, manifest.Repository, manifest.RepositoryID, manifest.RepositoryOwnerID, manifest.Organization, manifest.Cluster)
	for line := range strings.SplitSeq(strings.TrimSuffix(manifest.Policy, "\n"), "\n") {
		fmt.Fprintf(&output, "#   %s\n", line)
	}
	fmt.Fprintf(&output, `#
# Review and commit this file on %s. After a successful run, remove it.
name: Migrate GitHub secrets to Buildkite

on:
  workflow_dispatch:
    inputs:
      grant_id:
        description: One-use Buildkite migration grant
        required: true
        type: string

permissions:
  id-token: write

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      GRANT_ID: ${{ inputs.grant_id }}
`, manifest.DefaultBranch)
	for index, name := range manifest.SecretNames {
		fmt.Fprintf(&output, "      MIGRATION_SECRET_%03d: ${{ secrets.%s }}\n", index, name)
	}
	output.WriteString(`    steps:
      - name: Create Buildkite secrets
        shell: bash
        run: |
          set +x
          python3 - <<'PY'
          import json
          import os
          import re
          import sys
          import urllib.error
          import urllib.parse
          import urllib.request

          class NoRedirects(urllib.request.HTTPRedirectHandler):
              def redirect_request(self, request, file_pointer, code, message, headers, new_url):
                  return None

`)
	output.WriteString("          secrets = [\n")
	for index, name := range manifest.SecretNames {
		fmt.Fprintf(&output, "              (%q, %q),\n", name, fmt.Sprintf("MIGRATION_SECRET_%03d", index))
	}
	output.WriteString("          ]\n")
	migrationURLPrefix := fmt.Sprintf("https://api.buildkite.com/v2/organizations/%s/clusters/%s/github-actions-secret-migrations/", manifest.Organization, manifest.Cluster)
	fmt.Fprintf(&output, "          migration_url_prefix = %q\n", migrationURLPrefix)
	output.WriteString(`
          if os.environ.get("GITHUB_REF") != "refs/heads/" + os.environ.get("DEFAULT_BRANCH", ""):
              sys.exit("Run this migration from the repository default branch")
          grant_id = os.environ.get("GRANT_ID", "")
          if not re.fullmatch(r"[A-Za-z0-9_-]{16,200}", grant_id):
              sys.exit("The migration grant ID is invalid")

          values = {}
          for key, variable in secrets:
              value = os.environ.get(variable, "")
              size = len(value.encode("utf-8"))
              if not value.strip():
                  sys.exit(f"GitHub secret {key} is missing or empty; no Buildkite secrets were created")
              if size >= 32 * 1024:
                  sys.exit(f"GitHub secret {key} is too large for the Buildkite API; no Buildkite secrets were created")
              values[key] = value

          migration_url = migration_url_prefix + grant_id + "/secrets"
          audience = migration_url
          token_url = os.environ.get("ACTIONS_ID_TOKEN_REQUEST_URL", "")
          request_token = os.environ.get("ACTIONS_ID_TOKEN_REQUEST_TOKEN", "")
          if not token_url or not request_token:
              sys.exit("GitHub OIDC is unavailable")
          separator = "&" if "?" in token_url else "?"
          oidc_request = urllib.request.Request(
              token_url + separator + urllib.parse.urlencode({"audience": audience}),
              headers={"Authorization": f"Bearer {request_token}", "Accept": "application/json"},
          )
          opener = urllib.request.build_opener(NoRedirects)
          try:
              with opener.open(oidc_request, timeout=30) as response:
                  oidc_token = json.load(response).get("value", "")
          except Exception:
              sys.exit("Could not obtain GitHub OIDC identity")
          if not oidc_token:
              sys.exit("GitHub returned an empty OIDC identity")

          body = json.dumps({"secrets": values}, ensure_ascii=False).encode("utf-8")
          request = urllib.request.Request(
              migration_url,
              data=body,
              method="POST",
              headers={
                  "Authorization": f"Bearer {oidc_token}",
                  "Content-Type": "application/json",
                  "Accept": "application/json",
              },
          )
          try:
              with opener.open(request, timeout=30) as response:
                  if response.status != 201:
                      raise RuntimeError("unexpected response")
          except urllib.error.HTTPError as error:
              sys.exit(f"Buildkite rejected the migration with HTTP {error.code}; no existing value was overwritten")
          except Exception:
              sys.exit("The Buildkite migration request failed")

          for key in values:
              print(f"Created Buildkite secret {key}")
          print("Migration complete. Remove this workflow from the default branch.")
          PY
`)
	return []byte(output.String()), nil
}
